-- Challenge - Joining on multiple tables
-- Write SQL queries to perform the following tasks using the Sakila database:
use sakila;
-- List the number of films per category.
SELECT c.name AS category, COUNT(fc.film_id) AS number_of_films
FROM category c
JOIN film_category fc ON c.category_id = fc.category_id
GROUP BY c.name;

-- Retrieve the store ID, city, and country for each store.
select st.store_id, ct.city, country.country
from store st
join address on st.address_id = address.address_id
join city ct on address.city_id = ct.city_id
join country on ct.country_id = country.country_id
group by st.store_id;
-- Calculate the total revenue generated by each store in dollars.
select st.store_id, SUM(p.amount) as SUM_REV
from payment p
join rental r on p.rental_id = r.rental_id
join inventory i on r.inventory_id = i.inventory_id
join store st on i.store_id = st.store_id
group by st.store_id;
-- Determine the average running time of films for each category.
select c.name as category, avg(f.length) as AVG_LENG
from category c
JOIN film_category fc ON c.category_id = fc.category_id
join film f on f.film_id = fc.film_id
group by c.name
order by AVG_LENG desc;
-- Bonus:

-- Identify the film categories with the longest average running time.
select c.name as category, avg(f.length) as AVG_LENG
from category c
JOIN film_category fc ON c.category_id = fc.category_id
join film f on f.film_id = fc.film_id
group by c.name
order by AVG_LENG desc
limit 1;
-- Display the top 10 most frequently rented movies in descending order.
select f.title as Title, count(r.rental_id) as Rent_count
from film f
join inventory i on f.film_id = i.film_id
join rental r on i.inventory_id = r.inventory_id
group by f.title
order by Rent_count desc
limit 10;
-- Determine if "Academy Dinosaur" can be rented from Store 1.
select count(*) as avalible
from inventory i 
join film f on i.film_id = f.film_id
join store s on i.store_id = s.store_id
where f.title = "Academy Dinosaur" and s.store_id = 1; -- How many are avalible? 
-- Compare back to rental????????


-- Provide a list of all distinct film titles, along with their availability status in the inventory. Include a column indicating whether each title is 'Available' or 'NOT available.' Note that there are 42 titles that are not in the inventory, and this information can be obtained using a CASE statement combined with IFNULL."
select distinct f.title, 
	CASE
        WHEN ISNULL(i.inventory_id) THEN 'NOT available'
        ELSE 'Available'
    END AS Availability 
from film f
left join inventory i on i.film_id = f.film_id
group by f.title;
-- Here are some tips to help you successfully complete the lab:

-- Tip 1: This lab involves joins with multiple tables, which can be challenging. Take your time and follow the steps we discussed in class:

-- Make sure you understand the relationships between the tables in the database. This will help you determine which tables to join and which columns to use in your joins.
-- Identify a common column for both tables to use in the ON section of the join. If there isn't a common column, you may need to add another table with a common column.
-- Decide which table you want to use as the left table (immediately after FROM) and which will be the right table (immediately after JOIN).
-- Determine which table you want to include all records from. This will help you decide which type of JOIN to use. If you want all records from the first table, use a LEFT JOIN. If you want all records from the second table, use a RIGHT JOIN. If you want records from both tables only where there is a match, use an INNER JOIN.
-- Use table aliases to make your queries easier to read and understand. This is especially important when working with multiple tables.
-- Write the query
-- Tip 2: Break down the problem into smaller, more manageable parts. For example, you might start by writing a query to retrieve data from just two tables before adding additional tables to the join. Test your queries as you go, and check the output carefully to make sure it matches what you expect. This process takes time, so be patient and go step by step to build your query incrementally.

